language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
before_install:
 - pip install trollflow
install:
  - pip install .
  - pip install mock
  - pip install coveralls
script: coverage run --source=trollflow_sat setup.py test
after_success: coveralls
